# Oracle OCI Generative AI LangChain For Java version 1.0.
#
# Copyright (c)  2024,  Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
kind: Service
apiVersion: v1
metadata:
  name: langchain4java
  labels:
    app: langchain4java
spec:
  type: NodePort
  selector:
    app: langchain4java
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: langchain4java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langchain4java
  template:
    metadata:
      labels:
        app: langchain4java
        version: v1
    spec:
      containers:
      - name: langchain4java
        image: langchain4java
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
